// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfg7Ok1GRQWeq4ewcyABzfqb3mZvy7-1E',
    appId: '1:1079111524284:web:20b3797f41cb391d7f55b9',
    messagingSenderId: '1079111524284',
    projectId: 'tiffingo-d313a',
    authDomain: 'tiffingo-d313a.firebaseapp.com',
    storageBucket: 'tiffingo-d313a.firebasestorage.app',
    measurementId: 'G-E4H69EJTEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg8LSoiSNWtXLzpfdk8gdzcYIArP9jpEA',
    appId: '1:1079111524284:android:1dba2db1676275347f55b9',
    messagingSenderId: '1079111524284',
    projectId: 'tiffingo-d313a',
    storageBucket: 'tiffingo-d313a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmXDzAGgduuMvo441Kq1TAG3nQBhSLwMU',
    appId: '1:1079111524284:ios:16f87b56be326c1a7f55b9',
    messagingSenderId: '1079111524284',
    projectId: 'tiffingo-d313a',
    storageBucket: 'tiffingo-d313a.firebasestorage.app',
    iosBundleId: 'com.example.tiffin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmXDzAGgduuMvo441Kq1TAG3nQBhSLwMU',
    appId: '1:1079111524284:ios:16f87b56be326c1a7f55b9',
    messagingSenderId: '1079111524284',
    projectId: 'tiffingo-d313a',
    storageBucket: 'tiffingo-d313a.firebasestorage.app',
    iosBundleId: 'com.example.tiffin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfg7Ok1GRQWeq4ewcyABzfqb3mZvy7-1E',
    appId: '1:1079111524284:web:aca867fdc90b79867f55b9',
    messagingSenderId: '1079111524284',
    projectId: 'tiffingo-d313a',
    authDomain: 'tiffingo-d313a.firebaseapp.com',
    storageBucket: 'tiffingo-d313a.firebasestorage.app',
    measurementId: 'G-P55WP0414X',
  );
}
